from __future__ import annotations

import json
import re
import urllib.error
import urllib.request
from dataclasses import dataclass

from .config import OLLAMA_MODEL, OLLAMA_URL


@dataclass
class GeneratedAnswer:
    answer: str
    evidence: list[dict]


def build_context(
    evidence: list,
) -> str:
    parts = []

    for index, item in enumerate(
        evidence,
        start=1,
    ):
        section_text = ""

        if item.section:
            section_text = (
                f" | Section: {item.section}"
            )

        parts.append(
            f"[Source {index} | Page {item.page}"
            f"{section_text}]\n"
            f"{item.text.strip()}"
        )

    return "\n\n".join(parts)


def build_prompt(
    question: str,
    evidence: list,
) -> str:
    context = build_context(
        evidence,
    )

    return f"""
You are a research-paper question answering assistant.

Answer the user's question using ONLY the supplied evidence.

GROUNDING RULES:

1. Use only information explicitly supported by the supplied evidence.
2. Do not use outside knowledge.
3. Do not invent facts, explanations, examples, methods, results,
   references, or conclusions.
4. Every factual statement must be supported by the supplied evidence.
5. Prefer the most directly relevant evidence.
6. Combine overlapping evidence into one clear statement.
7. Do not repeat the same definition or idea using different wording
   from multiple evidence passages.
8. Do not copy long passages from the evidence.

METHOD HANDLING:

METHOD HANDLING:

9. When the question asks about research methods, distinguish
   methodological approaches from the topics or subjects being studied.

10. Report methods such as descriptive studies, theoretical approaches,
    empirical approaches, corpus-based methods, experimental approaches,
    case studies, error analysis, sociological or ethnographic approaches,
    and social network analysis only when supported by the evidence.

11. Do not describe research topics, application areas, training areas,
    digital genres, localization components, or quality issues as methods.

12. When the evidence contains both research areas and methods,
    prioritize the methodological information when answering a methods
    question.

13. When multiple distinct methodological approaches are explicitly
    supported by the evidence, include the major approaches represented
    across the retrieved passages rather than selecting only a few examples.

ANSWER STYLE:

11. Answer the user's question directly.
12. Keep the answer concise.
13. For a simple "What is...", "What does X mean?", or "Define X"
    question, answer in ONLY 2–3 sentences.
14. For a definition question, give the core definition first.
15. Include only the most important characteristics needed to explain
    the concept.
16. Do not list every example, application, genre, historical detail,
    or secondary point from the evidence.
17. Do not repeat the question.
18. Do not write a long paragraph when a short explanation is enough.
19. When the question asks for research methods, report methods or
    methodological approaches rather than simply listing research
    topics or areas.
20. When the evidence describes several methodological approaches,
    group them clearly instead of repeating similar descriptions.

CITATION RULES:

21. Do not reproduce academic citations from the source.
22. Never write citations such as:
    (Pym 2004)
    (Jiménez-Crespo 2016)
    (Microsoft 1994)
    (LISA 2003)
    (Pym 2011: 414)

23. Do not include author names or publication years unless the user
    specifically asks about them.
24. Page citations will be added automatically by the application.
25. Therefore, DO NOT write any page citations yourself.
26. Do not write [p. 3], [p. 4], or similar citations in your answer.

INSUFFICIENT EVIDENCE:

If the supplied evidence does not contain enough information to answer
the question, respond exactly:

The provided evidence does not contain enough information to answer this question.

QUESTION:

{question}

SUPPLIED EVIDENCE:

{context}

ANSWER:
""".strip()


def _clean_answer(
    answer: str,
) -> str:
    """
    Clean academic citations generated by the model.

    The original evidence is NOT modified.
    """

    # Remove parenthetical academic citations containing a year.
    answer = re.sub(
        r"\([^()\n]*\b(?:19|20)\d{2}\b[^()\n]*\)",
        "",
        answer,
    )

    # Remove common author/year citations without parentheses.
    answer = re.sub(
        r"\b(?:Microsoft|Pym|LISA|GALA|"
        r"Jiménez-Crespo|Esselink|Dunne|Mazur|"
        r"O'Hagan|Mangiron|Mayoral|Hurtado)"
        r"(?:\s+(?:&|and)\s+[\w'’-]+)?"
        r"\s+\d{4}(?::\s*\d+)?",
        "",
        answer,
        flags=re.IGNORECASE,
    )

    # Remove "cit. in" fragments.
    answer = re.sub(
        r"\bcit\.\s+in\b",
        "",
        answer,
        flags=re.IGNORECASE,
    )

    # Remove page citations if the model generated them.
    # The application adds its own page citations later.
    answer = re.sub(
        r"\[p\.\s*\d+(?:\s*;\s*p\.\s*\d+)*\]",
        "",
        answer,
        flags=re.IGNORECASE,
    )

    # Remove empty parentheses.
    answer = re.sub(
        r"\(\s*\)",
        "",
        answer,
    )

    # Normalize whitespace.
    answer = re.sub(
        r"[ \t]+",
        " ",
        answer,
    )

    # Remove spaces before punctuation.
    answer = re.sub(
        r"\s+([,.;:])",
        r"\1",
        answer,
    )

    # Normalize blank lines.
    answer = re.sub(
        r"\n{3,}",
        "\n\n",
        answer,
    )

    return answer.strip()


def _is_definition_question(
    question: str,
) -> bool:
    """
    Detect simple definition-style questions.
    """

    q = question.lower().strip()

    patterns = [
        r"^what is\b",
        r"^what does\b",
        r"^define\b",
        r"^what are\b.*\bdefinitions?\b",
        r"^what is meant by\b",
        r"^what does .* mean\b",
    ]

    return any(
        re.search(
            pattern,
            q,
        )
        for pattern in patterns
    )


def _limit_definition_answer(
    answer: str,
) -> str:
    """
    Keep simple definition answers concise.

    We prefer 2–3 sentences. If the model produces more,
    keep the first three meaningful sentences.
    """

    sentences = re.split(
        r"(?<=[.!?])\s+",
        answer.strip(),
    )

    sentences = [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]

    if len(sentences) <= 3:
        return answer.strip()

    return " ".join(
        sentences[:3]
    ).strip()


def _page_citation(
    evidence: list,
) -> str:
    """
    Build a page citation from the strongest supporting evidence.

    Duplicate pages are removed while preserving ranking order.
    """

    pages = []

    for item in evidence:
        page = int(item.page)

        if page not in pages:
            pages.append(page)

    if not pages:
        return ""

    page_text = "; ".join(
        f"p. {page}"
        for page in pages
    )

    return f"[{page_text}]"


def _attach_page_citation(
    answer: str,
    evidence: list,
) -> str:
    """
    Add page citations to the generated answer.

    The retrieved evidence is already ranked by relevance, so the
    strongest supporting pages are used as the citation set.
    """

    citation = _page_citation(
        evidence
    )

    if not citation:
        return answer.strip()

    answer = answer.strip()

    if not answer:
        return answer

    if answer.endswith(
        (".", "!", "?")
    ):
        return f"{answer} {citation}"

    return f"{answer}. {citation}"


def generate_answer(
    question: str,
    evidence: list,
) -> GeneratedAnswer:

    if not evidence:
        return GeneratedAnswer(
            answer=(
                "The provided evidence does not contain "
                "enough information to answer this question."
            ),
            evidence=[],
        )

    prompt = build_prompt(
        question,
        evidence,
    )

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.1,
        },
    }

    request = urllib.request.Request(
        OLLAMA_URL,
        data=json.dumps(
            payload
        ).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(
            request,
            timeout=180,
        ) as response:
            response_data = json.loads(
                response.read().decode(
                    "utf-8"
                )
            )

    except urllib.error.URLError as exc:
        raise RuntimeError(
            "Could not connect to Ollama. "
            "Make sure Ollama is running."
        ) from exc

    except json.JSONDecodeError as exc:
        raise RuntimeError(
            "Ollama returned an invalid response."
        ) from exc

    answer = response_data.get(
        "response",
        "",
    ).strip()

    if not answer:
        answer = (
            "The model did not generate an answer "
            "from the provided evidence."
        )

    # Clean citations and unnecessary formatting.
    answer = _clean_answer(
        answer,
    )

    # Keep simple definition questions short.
    if _is_definition_question(
        question
    ):
        answer = _limit_definition_answer(
            answer
        )

    # Add deterministic page citation.
    answer = _attach_page_citation(
        answer,
        evidence,
    )

    supporting_evidence = [
        {
            "page": item.page,
            "section": item.section,
            "score": round(
                float(item.score),
                3,
            ),
            "semantic_score": round(
                float(item.semantic_score),
                3,
            ),
            "keyword_score": round(
                float(item.keyword_score),
                3,
            ),
            "text": item.text,
        }
        for item in evidence
    ]

    return GeneratedAnswer(
        answer=answer,
        evidence=supporting_evidence,
    )